name: AWS Credentials
description: |
  This action is a wrapper for [aws-actions/configure-aws-credentials][aws-actions].

  ## Usage

  ```yaml
    steps:
      - name: AWS Credentials
        uses: tmknom/aws-credentials-action@v0
        with:
          aws-account-id: 123456789012
          iam-role-name: example-oidc-role
  ```

inputs:
  aws-account-id:
    required: true
    description: The number used to identify the Amazon Web Services account.
  iam-role-name:
    required: true
    description: The name of the role to assume.
  aws-region:
    default: us-east-1
    required: false
    description: The region to use.

outputs:
  session-name:
    value: ${{ steps.session.outputs.name }}
    description: Role session name.

runs:
  using: composite

  steps:
    - name: Describe repository name
      id: repo
      run: |
        set -x
        echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.iam-role-name }}
        role-session-name: ${{ steps.repo.outputs.name }}-${{ github.run_id }}-${{ github.run_attempt }}
        aws-region: ${{ inputs.aws-region }}
        mask-aws-account-id: true

    - name: Output session name
      id: session
      run: |
        set -x
        echo "name=$(aws sts get-caller-identity --query Arn --output text | cut -d/ -f3)" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Add job summary
      env:
        SESSION_NAME: ${{ steps.session.outputs.name }}
      run: |
        set -x
        {
          echo "### ✅ Authenticated with AWS"
          echo "#### CloudTrail"
          echo "- **URL**: https://console.aws.amazon.com/cloudtrail/home#/events?Username=${SESSION_NAME}"
          echo "#### User Identity"
          echo "- **Session Name**: \`${SESSION_NAME}\`"
        } >> "${GITHUB_STEP_SUMMARY}"
      shell: bash
