name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: least
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          iam-role-name: ${{ secrets.IAM_ROLE_NAME }}
          aws-region: ap-northeast-1

      - name: Verify
        env:
          SESSION_NAME: ${{ steps.exercise.outputs.session-name }}
        run: |
          set -x
          test "${SESSION_NAME}" = "aws-credentials-action-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
